"""Technology database — 40+ curated entries with scoring data.

This is a hand-curated, opinionated database, not a live feed.
github_stars values are point-in-time snapshots (last refreshed
2026-06-11) and drift over time. CVE entries are verified against the
GitHub Advisory Database / MITRE at the time of curation; always check
current advisories before deploying.
"""

from __future__ import annotations

TECH_DATABASE: dict[str, dict] = {
    # ═══ FRAMEWORKS ═══
    "next.js": {
        "aliases": ["nextjs", "next"],
        "category": "framework",
        "language": "javascript",
        "github_stars": 128000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": ["CVE-2025-29927"],
        "min_safe_version": "15.2.3",
        "pairs_well_with": ["tailwind", "supabase", "vercel", "stripe", "prisma", "trpc"],
        "conflicts_with": [],
        "learning_curve": 7,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 7,
        "hosting": ["vercel", "netlify", "docker", "node"],
        "description": "React framework with SSR, SSG, and API routes",
    },
    "astro": {
        "aliases": [],
        "category": "framework",
        "language": "javascript",
        "github_stars": 48000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["tailwind", "vercel", "netlify", "markdown"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 9,
        "hosting": ["vercel", "netlify", "cloudflare"],
        "description": "Content-focused framework, ships zero JS by default",
    },
    "nuxt": {
        "aliases": ["nuxt.js", "nuxtjs"],
        "category": "framework",
        "language": "javascript",
        "github_stars": 55000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["tailwind", "supabase", "vercel"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 8,
        "hosting": ["vercel", "netlify", "docker"],
        "description": "Vue.js meta-framework with SSR and auto-imports",
    },
    "sveltekit": {
        "aliases": ["svelte-kit", "svelte"],
        "category": "framework",
        "language": "javascript",
        "github_stars": 20500,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["tailwind", "supabase", "vercel"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 9,
        "hosting": ["vercel", "netlify", "cloudflare"],
        "description": "Svelte framework — compiled, fast, minimal runtime",
    },
    "fastapi": {
        "aliases": ["fast-api"],
        "category": "framework",
        "language": "python",
        "github_stars": 80000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["postgresql", "docker", "redis", "sqlalchemy"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 9,
        "hosting": ["docker", "hetzner", "aws", "railway"],
        "description": "Modern Python API framework with auto-docs",
    },
    "django": {
        "aliases": [],
        "category": "framework",
        "language": "python",
        "github_stars": 82000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": ["CVE-2024-45231"],
        "min_safe_version": "5.1.1",
        "pairs_well_with": ["postgresql", "redis", "docker", "htmx"],
        "conflicts_with": [],
        "learning_curve": 7,
        "performance": 7,
        "cost": "free",
        "cost_at_scale": 9,
        "hosting": ["docker", "hetzner", "aws", "railway"],
        "description": "Batteries-included Python web framework",
    },
    "express": {
        "aliases": ["express.js", "expressjs"],
        "category": "framework",
        "language": "javascript",
        "github_stars": 65000,
        "last_release": "2026-01",
        "maintained": True,
        "cves": ["CVE-2024-29041"],
        "min_safe_version": "4.19.2",
        "pairs_well_with": ["node", "mongodb", "postgresql"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 7,
        "cost": "free",
        "cost_at_scale": 8,
        "hosting": ["docker", "aws", "railway", "heroku"],
        "description": "Minimal Node.js web framework",
    },
    "flask": {
        "aliases": [],
        "category": "framework",
        "language": "python",
        "github_stars": 68000,
        "last_release": "2026-01",
        "maintained": True,
        "cves": ["CVE-2023-30861"],
        "min_safe_version": "2.3.2",
        "pairs_well_with": ["postgresql", "redis", "docker", "sqlalchemy"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 6,
        "cost": "free",
        "cost_at_scale": 8,
        "hosting": ["docker", "hetzner", "aws", "heroku"],
        "description": "Lightweight Python web framework",
    },

    # ═══ CSS / UI ═══
    "tailwind": {
        "aliases": ["tailwindcss", "tailwind-css"],
        "category": "css",
        "language": "css",
        "github_stars": 85000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "astro", "nuxt", "sveltekit", "react", "vue"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Utility-first CSS framework",
    },
    "shadcn": {
        "aliases": ["shadcn-ui", "shadcn/ui"],
        "category": "ui",
        "language": "javascript",
        "github_stars": 75000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "tailwind", "react"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Copy-paste UI components built on Radix + Tailwind",
    },

    # ═══ DATABASES ═══
    "supabase": {
        "aliases": ["@supabase/supabase-js"],
        "category": "database",
        "language": "sql",
        "github_stars": 75000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": ["CVE-2025-48370"],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "stripe", "vercel", "react-native"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 8,
        "cost": "freemium",
        "cost_at_scale": 7,
        "hosting": ["supabase-cloud", "self-hosted"],
        "description": "Open-source Firebase alternative with Postgres",
        "warnings": [
            "Enable RLS on ALL tables — many apps have been exposed without it",
            "Update @supabase/auth-js to >= 2.70.0 (CVE-2025-48370, low severity)",
        ],
    },
    "postgresql": {
        "aliases": ["postgres", "pg"],
        "category": "database",
        "language": "sql",
        "github_stars": 16000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "django", "next.js", "prisma", "sqlalchemy"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 9,
        "hosting": ["self-hosted", "supabase", "neon", "aws-rds"],
        "description": "World's most advanced open-source relational database",
    },
    "mongodb": {
        "aliases": ["mongo"],
        "category": "database",
        "language": "nosql",
        "github_stars": 27000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["express", "node", "mongoose"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 8,
        "cost": "freemium",
        "cost_at_scale": 6,
        "hosting": ["mongodb-atlas", "self-hosted"],
        "description": "Document database for flexible schemas",
    },
    "redis": {
        "aliases": [],
        "category": "database",
        "language": "key-value",
        "github_stars": 67000,
        "last_release": "2026-01",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "django", "next.js", "node"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 8,
        "hosting": ["upstash", "redis-cloud", "self-hosted"],
        "description": "In-memory data store for caching and queues",
    },
    "sqlite": {
        "aliases": [],
        "category": "database",
        "language": "sql",
        "github_stars": 0,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["python", "node", "turso"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 5,
        "hosting": ["embedded", "turso", "litestream"],
        "description": "Embedded SQL database — zero configuration",
    },

    # ═══ PAYMENTS ═══
    "stripe": {
        "aliases": [],
        "category": "payments",
        "language": "api",
        "github_stars": 4000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "supabase", "vercel"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 9,
        "cost": "2.9% + $0.30/tx",
        "cost_at_scale": 7,
        "hosting": [],
        "description": "Payment processing API",
        "warnings": ["Verify webhook signatures with stripe.webhooks.constructEvent()"],
    },
    "lemonsqueezy": {
        "aliases": ["lemon-squeezy"],
        "category": "payments",
        "language": "api",
        "github_stars": 2000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "vercel"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 8,
        "cost": "5% + $0.50/tx",
        "cost_at_scale": 5,
        "hosting": [],
        "description": "Payment + tax handling for SaaS — simpler than Stripe",
    },

    # ═══ HOSTING ═══
    "vercel": {
        "aliases": [],
        "category": "hosting",
        "language": "platform",
        "github_stars": 13000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "astro", "tailwind", "supabase"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 9,
        "cost": "freemium",
        "cost_at_scale": 5,
        "hosting": [],
        "description": "Frontend deployment platform — git push to deploy",
        "warnings": ["Can get expensive at 1M+ requests — watch bandwidth costs"],
    },
    "netlify": {
        "aliases": [],
        "category": "hosting",
        "language": "platform",
        "github_stars": 10000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["astro", "next.js", "nuxt"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 8,
        "cost": "freemium",
        "cost_at_scale": 6,
        "hosting": [],
        "description": "Web deployment with serverless functions",
    },
    "cloudflare": {
        "aliases": ["cloudflare-pages", "cloudflare-workers"],
        "category": "hosting",
        "language": "platform",
        "github_stars": 6000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["astro", "sveltekit", "hono"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 10,
        "cost": "freemium",
        "cost_at_scale": 9,
        "hosting": [],
        "description": "Edge computing platform — global, fast, cheap at scale",
    },
    "hetzner": {
        "aliases": [],
        "category": "hosting",
        "language": "platform",
        "github_stars": 0,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["docker", "fastapi", "django", "postgresql"],
        "conflicts_with": [],
        "learning_curve": 7,
        "performance": 9,
        "cost": "$4/mo VPS",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "European cloud provider — best price-to-performance",
    },
    "railway": {
        "aliases": [],
        "category": "hosting",
        "language": "platform",
        "github_stars": 5000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "django", "express", "postgresql"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 8,
        "cost": "usage-based",
        "cost_at_scale": 7,
        "hosting": [],
        "description": "Deploy any language — Heroku alternative",
    },

    # ═══ ORMs / DATA ═══
    "prisma": {
        "aliases": [],
        "category": "orm",
        "language": "javascript",
        "github_stars": 40000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "postgresql", "typescript"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Type-safe ORM for Node.js and TypeScript",
    },
    "drizzle": {
        "aliases": ["drizzle-orm"],
        "category": "orm",
        "language": "javascript",
        "github_stars": 25000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "postgresql", "sqlite", "typescript"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Lightweight TypeScript ORM — SQL-like, fast",
    },
    "sqlalchemy": {
        "aliases": [],
        "category": "orm",
        "language": "python",
        "github_stars": 10000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "flask", "postgresql"],
        "conflicts_with": [],
        "learning_curve": 7,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Python SQL toolkit and ORM",
    },

    # ═══ AUTH ═══
    "clerk": {
        "aliases": [],
        "category": "auth",
        "language": "api",
        "github_stars": 5000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "react"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 9,
        "cost": "freemium",
        "cost_at_scale": 6,
        "hosting": [],
        "description": "Drop-in auth with pre-built UI components",
    },
    "nextauth": {
        "aliases": ["next-auth", "authjs", "auth.js"],
        "category": "auth",
        "language": "javascript",
        "github_stars": 25000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "prisma", "supabase"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Authentication for Next.js — social login, JWT, sessions",
    },

    # ═══ LANGUAGES / RUNTIMES ═══
    "react": {
        "aliases": ["reactjs", "react.js"],
        "category": "library",
        "language": "javascript",
        "github_stars": 230000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": ["CVE-2025-55182"],
        "min_safe_version": "19.2.1",
        "pairs_well_with": ["next.js", "tailwind", "typescript"],
        "conflicts_with": ["vue", "svelte"],
        "learning_curve": 6,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "UI library for building component-based interfaces",
        "warnings": [
            "CVE-2025-55182 (critical RCE) affects the react-server-dom-webpack/"
            "-turbopack/-parcel RSC packages 19.0.0-19.2.0 — patch to 19.1.2/19.2.1"
        ],
    },
    "vue": {
        "aliases": ["vuejs", "vue.js"],
        "category": "library",
        "language": "javascript",
        "github_stars": 210000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["nuxt", "tailwind", "typescript"],
        "conflicts_with": ["react", "svelte"],
        "learning_curve": 4,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Progressive JavaScript framework",
    },
    "typescript": {
        "aliases": ["ts"],
        "category": "language",
        "language": "javascript",
        "github_stars": 102000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "react", "prisma", "trpc"],
        "conflicts_with": [],
        "learning_curve": 5,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Typed superset of JavaScript",
    },
    "python": {
        "aliases": ["py"],
        "category": "language",
        "language": "python",
        "github_stars": 65000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "django", "postgresql", "docker"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 6,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "General-purpose programming language",
    },
    "node": {
        "aliases": ["nodejs", "node.js"],
        "category": "runtime",
        "language": "javascript",
        "github_stars": 110000,
        "last_release": "2026-01",
        "maintained": True,
        "cves": ["CVE-2025-23083"],
        "min_safe_version": "22.13.1",
        "pairs_well_with": ["express", "next.js", "typescript"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 8,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "JavaScript runtime built on Chrome's V8 engine",
    },

    # ═══ DEVOPS / TOOLS ═══
    "docker": {
        "aliases": [],
        "category": "devops",
        "language": "devops",
        "github_stars": 70000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["fastapi", "django", "postgresql", "hetzner"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Container platform for consistent environments",
    },
    "trpc": {
        "aliases": ["t3-stack"],
        "category": "api",
        "language": "javascript",
        "github_stars": 35000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "typescript", "prisma"],
        "conflicts_with": [],
        "learning_curve": 6,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "End-to-end typesafe API layer",
    },

    # ═══ CLI TOOLING ═══
    "typer": {
        "aliases": [],
        "category": "cli",
        "language": "python",
        "github_stars": 19500,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["python", "rich"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Python CLI framework built on Click with type hints",
    },
    "rich": {
        "aliases": [],
        "category": "cli",
        "language": "python",
        "github_stars": 56500,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["python", "typer"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Rich text and beautiful formatting in the terminal",
    },

    # ═══ EMAIL ═══
    "resend": {
        "aliases": [],
        "category": "email",
        "language": "api",
        "github_stars": 3000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "react"],
        "conflicts_with": [],
        "learning_curve": 2,
        "performance": 9,
        "cost": "freemium",
        "cost_at_scale": 8,
        "hosting": [],
        "description": "Email API for developers — built by ex-Vercel",
    },

    # ═══ MONITORING ═══
    "sentry": {
        "aliases": [],
        "category": "monitoring",
        "language": "api",
        "github_stars": 40000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["next.js", "react", "fastapi", "django"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 9,
        "cost": "freemium",
        "cost_at_scale": 6,
        "hosting": ["sentry-cloud", "self-hosted"],
        "description": "Error tracking and performance monitoring",
    },

    # ═══ MOBILE ═══
    "react-native": {
        "aliases": ["rn"],
        "category": "mobile",
        "language": "javascript",
        "github_stars": 120000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["expo", "supabase", "stripe"],
        "conflicts_with": [],
        "learning_curve": 7,
        "performance": 7,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Build mobile apps with React",
    },
    "expo": {
        "aliases": [],
        "category": "mobile",
        "language": "javascript",
        "github_stars": 35000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["react-native", "supabase"],
        "conflicts_with": [],
        "learning_curve": 4,
        "performance": 8,
        "cost": "freemium",
        "cost_at_scale": 8,
        "hosting": ["expo-cloud"],
        "description": "React Native framework — OTA updates, managed builds",
    },

    # ═══ MISC ═══
    "markdown": {
        "aliases": ["md"],
        "category": "content",
        "language": "markup",
        "github_stars": 0,
        "last_release": "n/a",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["astro", "next.js"],
        "conflicts_with": [],
        "learning_curve": 1,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "Lightweight markup language for content",
    },
    "htmx": {
        "aliases": [],
        "category": "library",
        "language": "javascript",
        "github_stars": 40000,
        "last_release": "2026-02",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["django", "flask", "fastapi", "tailwind"],
        "conflicts_with": ["react", "vue"],
        "learning_curve": 3,
        "performance": 9,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": [],
        "description": "HTML-driven interactivity — no build step",
    },
    "hono": {
        "aliases": [],
        "category": "framework",
        "language": "javascript",
        "github_stars": 20000,
        "last_release": "2026-03",
        "maintained": True,
        "cves": [],
        "min_safe_version": None,
        "pairs_well_with": ["cloudflare", "typescript"],
        "conflicts_with": [],
        "learning_curve": 3,
        "performance": 10,
        "cost": "free",
        "cost_at_scale": 10,
        "hosting": ["cloudflare", "deno-deploy", "bun"],
        "description": "Ultra-fast web framework for the edge",
    },
}

PROVEN_STACKS = {
    "saas_starter": {
        "techs": ["next.js", "tailwind", "supabase", "stripe", "vercel"],
        "description": "The most common SaaS starter stack in 2026",
        "use_case": "SaaS products, web apps",
    },
    "blog": {
        "techs": ["astro", "tailwind", "markdown", "vercel"],
        "description": "Fast, SEO-friendly blog",
        "use_case": "Blogs, documentation sites",
    },
    "api_backend": {
        "techs": ["fastapi", "postgresql", "docker", "hetzner"],
        "description": "Production Python API backend",
        "use_case": "REST APIs, microservices",
    },
    "ecommerce": {
        "techs": ["next.js", "tailwind", "stripe", "supabase", "vercel"],
        "description": "Full-stack e-commerce",
        "use_case": "Online stores, marketplaces",
    },
    "mobile_app": {
        "techs": ["react-native", "expo", "supabase", "stripe"],
        "description": "Cross-platform mobile app",
        "use_case": "iOS + Android apps",
    },
    "cli_tool": {
        "techs": ["python", "typer", "rich"],
        "description": "Beautiful CLI tool",
        "use_case": "Developer tools, automation",
    },
    "landing_page": {
        "techs": ["astro", "tailwind", "vercel"],
        "description": "Fast landing page",
        "use_case": "Marketing pages, launch pages",
    },
    "t3_stack": {
        "techs": ["next.js", "typescript", "trpc", "prisma", "tailwind"],
        "description": "Full type-safety from database to frontend",
        "use_case": "Type-safe full-stack apps",
    },
    "django_fullstack": {
        "techs": ["django", "htmx", "tailwind", "postgresql", "docker"],
        "description": "Python full-stack without JS frameworks",
        "use_case": "Internal tools, admin panels",
    },
    "edge_first": {
        "techs": ["hono", "cloudflare", "drizzle", "sqlite"],
        "description": "Edge-first with minimal cost",
        "use_case": "APIs, lightweight web apps",
    },
}


def resolve_tech(name: str) -> str | None:
    """Resolve a tech name (including aliases) to its canonical name."""
    name_lower = name.lower().strip()
    if name_lower in TECH_DATABASE:
        return name_lower
    for canonical, data in TECH_DATABASE.items():
        if name_lower in [a.lower() for a in data.get("aliases", [])]:
            return canonical
    return None


def get_tech(name: str) -> dict | None:
    """Get tech data by name (resolves aliases)."""
    canonical = resolve_tech(name)
    if canonical:
        return TECH_DATABASE[canonical]
    return None
